import type { AdminRole } from "@prisma/client";
import {
  ADMIN_ROLE,
  ADMIN_MANAGER_ROLES,
  AUDIT_READER_ROLES,
  CREDENTIAL_MUTATOR_ROLES,
  CREDENTIAL_READER_ROLES,
  CREDENTIAL_REVOKER_ROLES,
  OWNER_ROLE,
  SUPER_ADMIN_ROLE,
} from "./admin-role.constants";

export const PERMISSION = {
  ADMIN_MANAGE: "ADMIN_MANAGE",
  ADMIN_READ: "ADMIN_READ",
  CREDENTIAL_CREATE: "CREDENTIAL_CREATE",
  CREDENTIAL_READ: "CREDENTIAL_READ",
  CREDENTIAL_UPDATE: "CREDENTIAL_UPDATE",
  CREDENTIAL_REVOKE: "CREDENTIAL_REVOKE",
  CREDENTIAL_DELETE: "CREDENTIAL_DELETE",
  DOCUMENT_PROOF_READ: "DOCUMENT_PROOF_READ",
  DOCUMENT_PROOF_CREATE: "DOCUMENT_PROOF_CREATE",
  DOCUMENT_PROOF_DELETE: "DOCUMENT_PROOF_DELETE",
  VERIFICATION_LOG_READ: "VERIFICATION_LOG_READ",
  AUDIT_LOG_READ: "AUDIT_LOG_READ",
  SETTINGS_READ: "SETTINGS_READ",
  SETTINGS_UPDATE: "SETTINGS_UPDATE",
} as const;

export type Permission = (typeof PERMISSION)[keyof typeof PERMISSION];

const ROLE_PERMISSIONS: Record<AdminRole, readonly Permission[]> = {
  OWNER: [
    PERMISSION.ADMIN_MANAGE,
    PERMISSION.ADMIN_READ,
    PERMISSION.CREDENTIAL_CREATE,
    PERMISSION.CREDENTIAL_READ,
    PERMISSION.CREDENTIAL_UPDATE,
    PERMISSION.CREDENTIAL_REVOKE,
    PERMISSION.CREDENTIAL_DELETE,
    PERMISSION.DOCUMENT_PROOF_READ,
    PERMISSION.DOCUMENT_PROOF_CREATE,
    PERMISSION.DOCUMENT_PROOF_DELETE,
    PERMISSION.VERIFICATION_LOG_READ,
    PERMISSION.AUDIT_LOG_READ,
    PERMISSION.SETTINGS_READ,
    PERMISSION.SETTINGS_UPDATE,
  ],
  SUPER_ADMIN: [
    PERMISSION.ADMIN_MANAGE,
    PERMISSION.ADMIN_READ,
    PERMISSION.CREDENTIAL_CREATE,
    PERMISSION.CREDENTIAL_READ,
    PERMISSION.CREDENTIAL_UPDATE,
    PERMISSION.CREDENTIAL_REVOKE,
    PERMISSION.CREDENTIAL_DELETE,
    PERMISSION.DOCUMENT_PROOF_READ,
    PERMISSION.DOCUMENT_PROOF_CREATE,
    PERMISSION.DOCUMENT_PROOF_DELETE,
    PERMISSION.VERIFICATION_LOG_READ,
    PERMISSION.AUDIT_LOG_READ,
    PERMISSION.SETTINGS_READ,
    PERMISSION.SETTINGS_UPDATE,
  ],
  ADMIN: [
    PERMISSION.CREDENTIAL_CREATE,
    PERMISSION.CREDENTIAL_READ,
    PERMISSION.CREDENTIAL_UPDATE,
    PERMISSION.DOCUMENT_PROOF_READ,
    PERMISSION.DOCUMENT_PROOF_CREATE,
    PERMISSION.VERIFICATION_LOG_READ,
    PERMISSION.AUDIT_LOG_READ,
    PERMISSION.SETTINGS_READ,
  ],
  AUDITOR: [
    PERMISSION.CREDENTIAL_READ,
    PERMISSION.DOCUMENT_PROOF_READ,
    PERMISSION.VERIFICATION_LOG_READ,
    PERMISSION.AUDIT_LOG_READ,
    PERMISSION.SETTINGS_READ,
  ],
} as const;

export function hasPermission(role: AdminRole, permission: Permission): boolean {
  const perms = ROLE_PERMISSIONS[role];
  return perms ? (perms as readonly string[]).includes(permission) : false;
}

export {
  OWNER_ROLE,
  SUPER_ADMIN_ROLE,
  ADMIN_ROLE,
  AUDIT_READER_ROLES,
  ADMIN_MANAGER_ROLES,
  CREDENTIAL_MUTATOR_ROLES,
  CREDENTIAL_REVOKER_ROLES,
  CREDENTIAL_READER_ROLES,
};
