import {
  PDFDocument,
  PDFPage,
  StandardFonts,
  rgb,
  type PDFImage,
  type PDFFont,
} from "pdf-lib";

interface CertificateIssuer {
  name: string;
  displayName: string | null;
  domain: string;
  logoUrl: string | null;
  websiteUrl: string | null;
}

interface CertificateInput {
  credentialId: string;
  verificationId: string;
  studentName: string;
  studentId: string;
  degree: string;
  issuedAt: Date;
  revoked: boolean;
  revokedAt: Date | null;
  issuer: CertificateIssuer;
  verificationUrl: string;
  qrCodePng: Buffer;
}

export async function generateCredentialCertificatePdf(input: CertificateInput) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([842, 595]);
  const width = page.getWidth();
  const height = page.getHeight();

  const serif = await pdf.embedFont(StandardFonts.TimesRomanBold);
  const sans = await pdf.embedFont(StandardFonts.Helvetica);
  const sansBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const qrImage = await pdf.embedPng(input.qrCodePng);
  const logoImage = await embedIssuerLogo(pdf, input.issuer.logoUrl);

  page.drawRectangle({
    x: 24,
    y: 24,
    width: width - 48,
    height: height - 48,
    color: rgb(0.992, 0.988, 0.976),
    borderColor: rgb(0.792, 0.745, 0.643),
    borderWidth: 1.25,
  });

  page.drawRectangle({
    x: 44,
    y: height - 108,
    width: width - 88,
    height: 1,
    color: rgb(0.824, 0.792, 0.722),
  });

  if (logoImage) {
    drawContainedImage(page, logoImage, 56, height - 98, 74, 74);
  }

  const issuerLabel = input.issuer.displayName ?? input.issuer.name;
  page.drawText(issuerLabel, {
    x: logoImage ? 142 : 58,
    y: height - 70,
    size: 24,
    font: sansBold,
    color: rgb(0.161, 0.173, 0.169),
  });

  page.drawText(input.issuer.domain, {
    x: logoImage ? 142 : 58,
    y: height - 92,
    size: 10,
    font: sans,
    color: rgb(0.384, 0.4, 0.4),
  });

  page.drawText("Academic Credential Certificate", {
    x: 58,
    y: height - 152,
    size: 30,
    font: serif,
    color: rgb(0.122, 0.141, 0.157),
  });

  page.drawText("This document certifies that", {
    x: 58,
    y: height - 198,
    size: 13,
    font: sans,
    color: rgb(0.384, 0.4, 0.4),
  });

  page.drawText(input.studentName, {
    x: 58,
    y: height - 236,
    size: 28,
    font: serif,
    color: rgb(0.09, 0.102, 0.114),
  });

  page.drawText("has been awarded", {
    x: 58,
    y: height - 276,
    size: 13,
    font: sans,
    color: rgb(0.384, 0.4, 0.4),
  });

  page.drawText(input.degree, {
    x: 58,
    y: height - 316,
    size: 22,
    font: sansBold,
    color: rgb(0.161, 0.173, 0.169),
  });

  page.drawText(
    "Verify this certificate using the QR code or verification URL shown on this document.",
    {
      x: 58,
      y: height - 350,
      size: 11,
      font: sans,
      color: rgb(0.443, 0.459, 0.467),
      maxWidth: 430,
      lineHeight: 14,
    },
  );

  drawInfoBlock(page, sans, sansBold, {
    x: 58,
    y: height - 430,
    width: 430,
    rows: [
      ["Credential ID", input.credentialId],
      ["Verification ID", input.verificationId],
      ["Student ID", input.studentId],
      ["Issued date", formatLongDate(input.issuedAt)],
      [
        "Credential status",
        input.revoked && input.revokedAt
          ? `Revoked on ${formatLongDate(input.revokedAt)}`
          : "Issued and active",
      ],
      ["Verification URL", input.verificationUrl],
    ],
  });

  page.drawRectangle({
    x: 538,
    y: 138,
    width: 246,
    height: 286,
    color: rgb(0.979, 0.972, 0.952),
    borderColor: rgb(0.867, 0.839, 0.765),
    borderWidth: 1,
  });

  page.drawText("Verification", {
    x: 562,
    y: 392,
    size: 16,
    font: sansBold,
    color: rgb(0.161, 0.173, 0.169),
  });

  page.drawText("Scan the QR code to review the live credential record.", {
    x: 562,
    y: 370,
    size: 10,
    font: sans,
    color: rgb(0.443, 0.459, 0.467),
    maxWidth: 196,
    lineHeight: 13,
  });

  drawContainedImage(page, qrImage, 576, 208, 170, 170);

  page.drawText(input.verificationId, {
    x: 562,
    y: 176,
    size: 11,
    font: sansBold,
    color: rgb(0.161, 0.173, 0.169),
  });

  page.drawText(input.issuer.websiteUrl ?? input.issuer.domain, {
    x: 58,
    y: 72,
    size: 10,
    font: sans,
    color: rgb(0.443, 0.459, 0.467),
  });

  page.drawText("Generated by Certiva credential registry", {
    x: width - 248,
    y: 72,
    size: 10,
    font: sans,
    color: rgb(0.443, 0.459, 0.467),
  });

  return pdf.save();
}

function drawInfoBlock(
  page: PDFPage,
  sans: PDFFont,
  sansBold: PDFFont,
  input: {
    x: number;
    y: number;
    width: number;
    rows: Array<[string, string]>;
  },
) {
  const rowHeight = 32;

  page.drawRectangle({
    x: input.x,
    y: input.y,
    width: input.width,
    height: rowHeight * input.rows.length + 8,
    color: rgb(0.979, 0.972, 0.952),
    borderColor: rgb(0.867, 0.839, 0.765),
    borderWidth: 1,
  });

  input.rows.forEach(([label, value], index) => {
    const rowY = input.y + rowHeight * (input.rows.length - index - 1);

    if (index > 0) {
      page.drawRectangle({
        x: input.x + 18,
        y: rowY + rowHeight - 1,
        width: input.width - 36,
        height: 1,
        color: rgb(0.914, 0.886, 0.816),
      });
    }

    page.drawText(label, {
      x: input.x + 18,
      y: rowY + 18,
      size: 8,
      font: sansBold,
      color: rgb(0.443, 0.459, 0.467),
    });

    page.drawText(value, {
      x: input.x + 150,
      y: rowY + 16,
      size: 9,
      font: sans,
      color: rgb(0.161, 0.173, 0.169),
      maxWidth: input.width - 170,
      lineHeight: 11,
    });
  });
}

async function embedIssuerLogo(pdf: PDFDocument, logoUrl: string | null) {
  if (!logoUrl) {
    return null;
  }

  try {
    const response = await fetch(logoUrl);
    if (!response.ok) {
      return null;
    }

    const imageBytes = await response.arrayBuffer();
    const contentType = response.headers.get("content-type") ?? "";
    if (contentType.includes("png")) {
      return pdf.embedPng(imageBytes);
    }

    if (contentType.includes("jpeg") || contentType.includes("jpg")) {
      return pdf.embedJpg(imageBytes);
    }

    return null;
  } catch {
    return null;
  }
}

function drawContainedImage(
  page: PDFPage,
  image: PDFImage,
  x: number,
  y: number,
  maxWidth: number,
  maxHeight: number,
) {
  const scaled = image.scale(1);
  const ratio = Math.min(maxWidth / scaled.width, maxHeight / scaled.height);
  const width = scaled.width * ratio;
  const height = scaled.height * ratio;

  page.drawImage(image, {
    x: x + (maxWidth - width) / 2,
    y: y + (maxHeight - height) / 2,
    width,
    height,
  });
}

function formatLongDate(value: Date) {
  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(value);
}
